=== gatekeep06/neuromon/common/scemas/species.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/schemas/entity.schema.json",
    "$defs": {
        "stats": {
            "type": "object",
            "properties": {
                "hp": { "type": "integer" },
                "attack": { "type": "integer" },
                "defence": { "type": "integer" },
                "special_attack": { "type": "integer" },
                "special_defence": { "type": "integer" },
                "speed": { "type": "integer" }
            }
        }
    },
    "type": "object",
    "properties": {
        "name": { "type": "string" },
        "nationalPokedexNumber": { "type": "integer" },
        "baseStats": { "$ref": "#/$defs/stats" },
        "maleRatio": { "type": "number", "minimum": -1.0, "maximum": 1.0 },
        "catchRate": { "type": "integer" },
        "baseScale": { "type": "number" },
        "baseExperienceYield": { "type": "integer" },
        "baseFriendship": { "type": "integer" },
        "evYield": { "$ref": "#/$defs/stats" },
        "experienceGroup": {
            "type": "string",
            "enum": ["erratic", "fast", "medium_fast", "medium_slow", "slow", "fluctuating"]
        },
        "hitbox": {
            "type": "object",
            "properties": {
                "width": { "type": "number" },
                "height": { "type": "number" },
                "eyeHeight": { "type": "number" },
                "fixed": { "type": "boolean" }
            }
        },
        "primaryType": { "type": "string" },
        "secondaryType": { "type": "string" },
        "abilities": {
            "type": "array",
            "items": { "type": "string" }
        },
        "shoulderMountable": { "type": "boolean" },
        "shoulderEffects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": { "type": "string", "examples": ["potion_effect"] },
                    "effect": { "type": "string" },
                    "amplifier": { "type": "number" },
                    "ambient": { "type": "boolean" },
                    "showParticles": { "type":  "boolean"},
                    "showIcon": { "type": "boolean" }
                }
            }
        },
        "moves": {
            "type": "array",
            "items": { "type": "string" }
        },
        "features": {
            "type": "array",
            "items": { "type": "string" }
        },
        "standingEyeHeight": { "type": "number" },
        "swimmingEyeHeight": { "type": "number" },
        "flyingEyeHeight": { "type": "number" },
        "behaviour": {
            "type": "object",
            "properties": {
                "resting": {
                    "type": "object",
                    "properties": {
                        "canSleep": { "type": "boolean" },
                        "times": { "type": "string" },
                        "blocks": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "biomes": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "fluids": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "light": { "type": "string" },
                        "depth": { "type": "string", "examples": ["comatose", "normal"] },
                        "canSeeSky": { "type": "boolean" },
                        "skyLight": { "type": "string" },
                        "drowsyChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 },
                        "rouseChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 }
                    }
                },
                "moving": {
                    "type": "object",
                    "properties": {
                        "walk": {
                            "type": "object",
                            "properties": {
                                "canWalk": { "type": "boolean" },
                                "avoidsLand": { "type": "boolean" },
                                "walkSpeed": { "type": "string" }
                            }
                        },
                        "swim": {
                            "type": "object",
                            "properties": {
                                "avoidsWater": { "type": "boolean" },
                                "canSwimInWater": { "type": "boolean" },
                                "swimSpeed": { "type": "string" },
                                "canBreatheUnderwater": { "type": "boolean" },
                                "canWalkOnWater": { "type": "boolean" },
                                "canSwimInLava": { "type": "boolean" },
                                "canBreatheUnderlava": { "type": "boolean" },
                                "canWalkOnLava": { "type": "boolean" }
                            }
                        },
                        "fly": {
                            "type": "object",
                            "properties": {
                                "canFly": { "type": "boolean" },
                                "flySpeedHorizontal": { "type": "string" }
                            }
                        },
                        "stepHeight": { "type": "number" },
                        "wanderChance": { "type": "integer" },
                        "wanderSpeed": { "type": "number" },
                        "canLook": { "type": "boolean" }
                    }
                },
                "idle": {
                    "type": "object",
                    "properties": {}
                },
                "fireImmune": { "type": "boolean" },
                "dampensVibrations": { "type": "boolean" },
                "entityInteract": {
                    "type": "object",
                    "properties": {
                        "avoidedByCreeper": { "type": "boolean" },
                        "avoidedByPhantom": { "type": "boolean" },
                        "avoidedByFox": { "type": "boolean" },
                        "avoidedBySkeleton": { "type": "boolean" }
                    }
                },
                "lightningHit": {
                    "type": "object",
                    "properties": {
                        "rotateFeatures": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": { "type": "string" },
                                    "chain": { 
                                        "type": "array",
                                        "items": { "type": "string" }
                                    }
                                }
                            }
                        }
                    }
                },
                "blockInteract": {
                    "type": "object",
                    "properties": {
                        "immuneToSweetBerryBushBlock": { "type": "boolean" },
                        "canStandOnPowderSnow": { "type": "boolean" },
                        "canPathThroughSaccLeaves": { "type": "boolean" }
                    }
                },
                "combat": {
                    "type": "object",
                    "properties": {
                        "willDefendSelf": { "type": "boolean" },
                        "willFlee": { "type": "boolean" },
                        "willDefendOwner": { "type": "boolean" },
                        "fightsMelee": { "type": "boolean" }
                    }
                },
                "herd": {
                    "type": "object",
                    "properties": {
                        "toleratedLeaders": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "pokemon": { "type": "string" },
                                    "tier": { "type": "integer" },
                                    "ignoresLevel": { "type": "boolean" },
                                    "followDistance": { "type": "string" }
                                }
                            }
                        },
                        "maxSize": {"type": "integer" },
                        "followDistance": { "type": "string" }
                    }
                },
                "characteristicRainbow": { "type": "boolean" },
                "itemInteract": {
                    "type": "object",
                    "properties": {
                        "desiredItems": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "item": { "type": "string" },
                                    "pickupPriority": { "type": "integer" },
                                    "fullnessValue": { "type": "integer" },
                                    "returnItem": { "type": "string" },
                                    "onUseEffect": { "type": "string"}
                                }
                            }
                        }
                    }
                }
            }
        },
        "pokedex": {
            "type": "array",
            "items": { "type": "string" }
        },
        "drops": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "amount": { "type": "string" }
            }
        },
        "eggCycles": { "type": "integer" },
        "eggGroups": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["monster", "water_1", "bug", "flying", "field", "fairy", "grass", "human_like", "water_3", "mineral", "amorphous", "water_2", "ditto", "dragon", "undiscovered"]
            }
        },
        "dynamaxBlocked": { "type": "boolean" },
        "implemented": { "type": "boolean" },
        "baseAI": {
            "type": "array",
            "items": { "type": "object" }
        },
        "ai": {
            "type": "array",
            "items": { "type": "object" }
        },
        "height": { "type": "number" },
        "weight": { "type": "number" },
        "forms": {
            "type": "array",
            "items": { "type": "object" }
        },
        "riding": { "type": "object" },
        "labels": {
            "type": "array",
            "items": { "type": "string" }
        },
        "evolutions": {
            "type": "array",
            "items": { "type": "object" }
        },
        "preEvolution": { "type": "string" },
        "battleTheme": { "type": "string" },
        "lightingData": {
            "type": "object",
            "properties": {
                "lightLevel": { "type": "integer" },
                "liquidGlowMode": {
                    "type": "string",
                    "enum": ["LAND", "UNDERWATER", "BOTH"]
                }
            }
        }
    }
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/studysama.json
{
    "name": "Studysama",
    "nationalPokedexNumber": 2121,
    "baseStats": {
        "hp": 21,
        "attack": 21,
        "defence": 21,
        "special_attack": 21,
        "special_defence": 21,
        "speed": 21
    },
    "maleRatio": 0.0,
    "catchRate": 3,
    "baseScale": 0.6,
    "baseExperienceYield": 40,
    "baseFriendship": 0,
    "evYield": {
        "hp": 1
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 0.75,
        "height": 1.1,
        "fixed": false
    },
    "primaryType": "ghost",
    "abilities": [
        "cursedbody",
        "h:cursedbody"
    ],
    "shoulderMountable": true,
    "moves": [
        "1:teleport",
        "6:confuseray",
        "24:nightshade",
        "24:shadowsneak",
        "36:hex",
        "tutor:poltergeist"
    ],
    "features": [],
    "behaviour": {
        "moving": {
            "walk": {
                "walkSpeed": "0.2"
            },
            "fly": {
                "canFly": true,
                "flySpeedHorizontal": "0.4"
            }
        },
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        },
        "blockInteract": {
            "immuneToSweetBerryBushBlock": true,
            "canStandOnPowderSnow": true
        },
        "combat": {
            "willFlee": false
        }
    },
    "pokedex": [
        "cobblemon.species.studysama.desc"
    ],
    "drops": {
        "amount": "2",
        "entries": [
            {
                "item": "cobblemon:spell_tag",
                "percentage": 25
            },
            {
                "item": "cobblemon:payapa_berry",
                "percentage": 20
            },
            {
                "item": "minecraft:phantom_membrane",
                "quantityRange": "1-3"
            }
        ]
    },
    "eggGroups": ["undiscovered"],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 5,
    "weight": 5,
    "forms": [],
    "labels": [
        "custom",
        "neuroverse",
        "baby"
    ],
    "evolutions": [
        {
            "id": "studysama_neuroplushie",
            "variant": "level_up",
            "result": "neuroplushie",
            "consumeHeldItem": false,
            "learnableMoves": [
                "sistertherapy"
            ],
            "requirements": [
                {
                    "variant": "friendship",
                    "amount": 160
                },
                {
                    "variant": "party_member",
                    "target": "vedal"
                },
                {
                    "variant": "time_range",
                    "range": "day"
                }
            ]
        },
        {
            "id": "studysama_evilplushie",
            "variant": "level_up",
            "result": "evilplushie",
            "consumeHeldItem": false,
            "learnableMoves": [
                "sistertherapy"
            ],
            "requirements": [
                {
                    "variant": "friendship",
                    "amount": 160
                },
                {
                    "variant": "party_member",
                    "target": "vedal"
                },
                {
                    "variant": "time_range",
                    "range": "night"
                }
            ]
        }
    ],
    "lightingData": {
        "lightLevel": 5,
        "liquidGlowMode": "BOTH"
    }
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/minawan.json
{
    "name": "Minawan",
    "nationalPokedexNumber": 2131,
    "baseStats": {
        "hp": 80,
        "attack": 95,
        "defence": 70,
        "special_attack": 40,
        "special_defence": 70,
        "speed": 85
    },
    "maleRatio": 0.5,
    "catchRate": 90,
    "baseScale": 0.75,
    "baseExperienceYield": 40,
    "baseFriendship": 50,
    "evYield": {
        "hp": 1
    },
    "experienceGroup": "medium_fast",
    "hitbox": {
        "width": 1,
        "height": 1,
        "fixed": false
    },
    "primaryType": "normal",
    "abilities": [
        "scrappy",
        "h:guarddog"
    ],
    "moves": [

    ],
    "features": [],
    "behaviour": {

    },
    "pokedex": [

    ],
    "drops": {

    },
    "eggCycles": 120,
    "eggGroups": ["field", "fairy"],
    "dynamaxBlocked": false,
    "implemented": false,
    "height": 1,
    "weight": 1,
    "forms": [
        {
            "name": "Fire",
            "primaryType": "fire",
            "aspects": [
                "fire-minawan"
            ],
            "abilities": [
                "flashfire",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Water",
            "primaryType": "water",
            "aspects": [
                "water-minawan"
            ],
            "abilities": [
                "waterabsorb",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Grass",
            "primaryType": "grass",
            "aspects": [
                "grass-minawan"
            ],
            "abilities": [
                "chlorophyll",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Electric",
            "primaryType": "electric",
            "aspects": [
                "electric-minawan"
            ],
            "abilities": [
                "voltabsorb",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Ice",
            "primaryType": "ice",
            "aspects": [
                "ice-minawan"
            ],
            "abilities": [
                "icebody",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Fighting",
            "primaryType": "fighting",
            "aspects": [
                "fighting-minawan"
            ],
            "abilities": [
                "innerfocus",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Poison",
            "primaryType": "poison",
            "aspects": [
                "poison-minawan"
            ],
            "abilities": [
                "poisonpoint",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Ground",
            "primaryType": "ground",
            "aspects": [
                "ground-minawan"
            ],
            "abilities": [
                "sandforce",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Flying",
            "primaryType": "flying",
            "aspects": [
                "flying-minawan"
            ],
            "abilities": [
                "hustle",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Psychic",
            "primaryType": "psychic",
            "aspects": [
                "psychic-minawan"
            ],
            "abilities": [
                "synchronize",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Bug",
            "primaryType": "bug",
            "aspects": [
                "bug-minawan"
            ],
            "abilities": [
                "shielddust",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Rock",
            "primaryType": "rock",
            "aspects": [
                "rock-minawan"
            ],
            "abilities": [
                "sandrush",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Ghost",
            "primaryType": "ghost",
            "aspects": [
                "ghost-minawan"
            ],
            "abilities": [
                "levitate",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Dragon",
            "primaryType": "dragon",
            "aspects": [
                "dragon-minawan"
            ],
            "abilities": [
                "roughskin",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Dark",
            "primaryType": "dark",
            "aspects": [
                "dark-minawan"
            ],
            "abilities": [
                "intimidate",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Steel",
            "primaryType": "steel",
            "aspects": [
                "steel-minawan"
            ],
            "abilities": [
                "heavymetal",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        },
        {
            "name": "Fairy",
            "primaryType": "fairy",
            "aspects": [
                "fairy-minawan"
            ],
            "abilities": [
                "magicguard",
                "h:guarddog"
            ],
            "drops": {

            },
            "moves": [

            ],
            "battleOnly": false
        }
    ],
    "labels": [
        "custom",
        "neuroverse"
    ]
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/vedal.json
{
    "name": "Vedal",
    "nationalPokedexNumber": 2126,
    "baseStats": {
        "hp": 120,
        "attack": 60,
        "defence": 100,
        "special_attack": 40,
        "special_defence": 100,
        "speed": 30
    },
    "maleRatio": 1.0,
    "catchRate": 45,
    "baseScale": 0.6,
    "baseExperienceYield": 160,
    "baseFriendship": 50,
    "evYield": {
        "hp": 2
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 1,
        "height": 1.6,
        "fixed": false
    },
    "primaryType": "fighting",
    "abilities": [
        "shellarmor",
        "sturdy",
        "h:fatheroftheyear"
    ],
    "shoulderMountable": true,
    "moves": [

    ],
    "features": [],
    "behaviour": {
        "resting": {
            "canSleep": true,
            "willSleepOnBed": true,
            "depth": "normal",
            "light": "0-4"
        },
        "moving": {
            "walk": {
                "walkSpeed": "0.2"
            }
        },
        "herd": {
            "maxSize": 5
        }
    },
    "pokedex": [
        "cobblemon.species.vedal.desc"
    ],
    "drops": {

    },
    "eggCycles": 45,
    "eggGroups": [
        "field"
    ],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 7,
    "weight": 907,
    "forms": [
        {
            "name": "Giga",
            "baseStats": {
                "hp": 120,
                "attack": 150,
                "defence": 110,
                "special_attack": 65,
                "special_defence": 110,
                "speed": 95
            },
            "baseScale": 1.0,
            "hitbox": {
                "width": 2,
                "height": 2,
                "fixed": false
            },
            "shoulderMountable": false,
            "height": 25,
            "weight": 3527,
            "battleOnly": true
        }
    ],
    "labels": [
        "custom",
        "neuroverse"
    ]
}
