=== gatekeep06/neuromon/common/scemas/species.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/schemas/entity.schema.json",
    "$defs": {
        "stats": {
            "type": "object",
            "properties": {
                "hp": { "type": "integer" },
                "attack": { "type": "integer" },
                "defence": { "type": "integer" },
                "special_attack": { "type": "integer" },
                "special_defence": { "type": "integer" },
                "speed": { "type": "integer" }
            }
        }
    },
    "type": "object",
    "properties": {
        "name": { "type": "string" },
        "nationalPokedexNumber": { "type": "integer" },
        "baseStats": { "$ref": "#/$defs/stats" },
        "maleRatio": { "type": "number", "minimum": -1.0, "maximum": 1.0 },
        "catchRate": { "type": "integer" },
        "baseScale": { "type": "number" },
        "baseExperienceYield": { "type": "integer" },
        "baseFriendship": { "type": "integer" },
        "evYield": { "$ref": "#/$defs/stats" },
        "experienceGroup": {
            "type": "string",
            "enum": ["erratic", "fast", "medium_fast", "medium_slow", "slow", "fluctuating"]
        },
        "hitbox": {
            "type": "object",
            "properties": {
                "width": { "type": "number" },
                "height": { "type": "number" },
                "eyeHeight": { "type": "number" },
                "fixed": { "type": "boolean" }
            }
        },
        "primaryType": { "type": "string" },
        "secondaryType": { "type": "string" },
        "abilities": {
            "type": "array",
            "items": { "type": "string" }
        },
        "shoulderMountable": { "type": "boolean" },
        "shoulderEffects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": { "type": "string", "examples": ["potion_effect"] },
                    "effect": { "type": "string" },
                    "amplifier": { "type": "number" },
                    "ambient": { "type": "boolean" },
                    "showParticles": { "type":  "boolean"},
                    "showIcon": { "type": "boolean" }
                }
            }
        },
        "moves": {
            "type": "array",
            "items": { "type": "string" }
        },
        "features": {
            "type": "array",
            "items": { "type": "string" }
        },
        "standingEyeHeight": { "type": "number" },
        "swimmingEyeHeight": { "type": "number" },
        "flyingEyeHeight": { "type": "number" },
        "behaviour": {
            "type": "object",
            "properties": {
                "resting": {
                    "type": "object",
                    "properties": {
                        "canSleep": { "type": "boolean" },
                        "times": { "type": "string" },
                        "blocks": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "biomes": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "fluids": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "light": { "type": "string" },
                        "depth": { "type": "string", "examples": ["comatose", "normal"] },
                        "canSeeSky": { "type": "boolean" },
                        "skyLight": { "type": "string" },
                        "drowsyChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 },
                        "rouseChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 }
                    }
                },
                "moving": {
                    "type": "object",
                    "properties": {
                        "walk": {
                            "type": "object",
                            "properties": {
                                "canWalk": { "type": "boolean" },
                                "avoidsLand": { "type": "boolean" },
                                "walkSpeed": { "type": "string" }
                            }
                        },
                        "swim": {
                            "type": "object",
                            "properties": {
                                "avoidsWater": { "type": "boolean" },
                                "canSwimInWater": { "type": "boolean" },
                                "swimSpeed": { "type": "string" },
                                "canBreatheUnderwater": { "type": "boolean" },
                                "canWalkOnWater": { "type": "boolean" },
                                "canSwimInLava": { "type": "boolean" },
                                "canBreatheUnderlava": { "type": "boolean" },
                                "canWalkOnLava": { "type": "boolean" }
                            }
                        },
                        "fly": {
                            "type": "object",
                            "properties": {
                                "canFly": { "type": "boolean" },
                                "flySpeedHorizontal": { "type": "string" }
                            }
                        },
                        "stepHeight": { "type": "number" },
                        "wanderChance": { "type": "integer" },
                        "wanderSpeed": { "type": "number" },
                        "canLook": { "type": "boolean" }
                    }
                },
                "idle": {
                    "type": "object",
                    "properties": {}
                },
                "fireImmune": { "type": "boolean" },
                "dampensVibrations": { "type": "boolean" },
                "entityInteract": {
                    "type": "object",
                    "properties": {
                        "avoidedByCreeper": { "type": "boolean" },
                        "avoidedByPhantom": { "type": "boolean" },
                        "avoidedByFox": { "type": "boolean" },
                        "avoidedBySkeleton": { "type": "boolean" }
                    }
                },
                "lightningHit": {
                    "type": "object",
                    "properties": {
                        "rotateFeatures": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": { "type": "string" },
                                    "chain": { 
                                        "type": "array",
                                        "items": { "type": "string" }
                                    }
                                }
                            }
                        }
                    }
                },
                "blockInteract": {
                    "type": "object",
                    "properties": {
                        "immuneToSweetBerryBushBlock": { "type": "boolean" },
                        "canStandOnPowderSnow": { "type": "boolean" },
                        "canPathThroughSaccLeaves": { "type": "boolean" }
                    }
                },
                "combat": {
                    "type": "object",
                    "properties": {
                        "willDefendSelf": { "type": "boolean" },
                        "willFlee": { "type": "boolean" },
                        "willDefendOwner": { "type": "boolean" },
                        "fightsMelee": { "type": "boolean" }
                    }
                },
                "herd": {
                    "type": "object",
                    "properties": {
                        "toleratedLeaders": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "pokemon": { "type": "string" },
                                    "tier": { "type": "integer" },
                                    "ignoresLevel": { "type": "boolean" },
                                    "followDistance": { "type": "string" }
                                }
                            }
                        },
                        "maxSize": {"type": "integer" },
                        "followDistance": { "type": "string" }
                    }
                },
                "characteristicRainbow": { "type": "boolean" },
                "itemInteract": {
                    "type": "object",
                    "properties": {
                        "desiredItems": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "item": { "type": "string" },
                                    "pickupPriority": { "type": "integer" },
                                    "fullnessValue": { "type": "integer" },
                                    "returnItem": { "type": "string" },
                                    "onUseEffect": { "type": "string"}
                                }
                            }
                        }
                    }
                }
            }
        },
        "pokedex": {
            "type": "array",
            "items": { "type": "string" }
        },
        "drops": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "amount": { "type": "string" }
            }
        },
        "eggCycles": { "type": "integer" },
        "eggGroups": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["monster", "water_1", "bug", "flying", "field", "fairy", "grass", "human_like", "water_3", "mineral", "amorphous", "water_2", "ditto", "dragon", "undiscovered"]
            }
        },
        "dynamaxBlocked": { "type": "boolean" },
        "implemented": { "type": "boolean" },
        "baseAI": {
            "type": "array",
            "items": { "type": "object" }
        },
        "ai": {
            "type": "array",
            "items": { "type": "object" }
        },
        "height": { "type": "number" },
        "weight": { "type": "number" },
        "forms": {
            "type": "array",
            "items": { "type": "object" }
        },
        "riding": { "type": "object" },
        "labels": {
            "type": "array",
            "items": { "type": "string" }
        },
        "evolutions": {
            "type": "array",
            "items": { "type": "object" }
        },
        "preEvolution": { "type": "string" },
        "battleTheme": { "type": "string" },
        "lightingData": {
            "type": "object",
            "properties": {
                "lightLevel": { "type": "integer" },
                "liquidGlowMode": {
                    "type": "string",
                    "enum": ["LAND", "UNDERWATER", "BOTH"]
                }
            }
        }
    }
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/evilplushie.json
{
    "name": "Evilplushie",
    "nationalPokedexNumber": 2123,
    "baseStats": {
        "hp": 80,
        "attack": 95,
        "defence": 80,
        "special_attack": 45,
        "special_defence": 75,
        "speed": 65
    },
    "maleRatio": 0.0,
    "catchRate": 190,
    "baseScale": 0.6,
    "baseExperienceYield": 40,
    "baseFriendship": 50,
    "evYield": {
        "attack": 2
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 1,
        "height": 1,
        "fixed": false
    },
    "primaryType": "dark",
    "abilities": [
        "prankster",
        "h:prankster"
    ],
    "shoulderMountable": true,
    "moves": [
        "1:scratch",
        "1:flatter",
        "1:swagger",
        "1:leer",
        "5:brutalswing",
        "10:knockoff",
        "12:snarl",
        "18:meanlook",
        "21:frustration",
        "25:alluringvoice",
        "28:faketears",
        "32:torment",
        "36:screech",
        "42:beatup",
        "50:stompingtantrum",
        "56:outrage",
        "60:foulplay",
        "65:spiritbreak",
        "85:bulkup",
        "tm:teleport",
        "tm:confuseray",
        "tm:nightshade",
        "tm:shadowsneak",
        "tm:thief",
        "tm:takedown",
        "tm:protect",
        "tm:metronome",
        "tm:rest",
        "tm:sleeptalk",
        "tm:bodyslam",
        "tm:bodypress",
        "tm:taunt",
        "tm:substitute",
        "tm:focusblast",
        "tm:voltswitch",
        "tm:nastyplot",
        "tm:throatchop",
        "tm:playrough",
        "tm:lashout",
        "tm:disarmingvoice",
        "tm:sing",
        "tm:boomburst",
        "tm:psychicnoise",
        "tm:brickbreak",
        "tm:firepunch",
        "tm:thunderpunch",
        "tm:icepunch",
        "tm:fling",
        "tm:trick",
        "tm:imprison",
        "tm:shadowclaw",
        "tm:reflect",
        "tm:lightscreen",
        "tm:trailblaze",
        "tm:willowisp",
        "tm:darkpulse",
        "tm:burningjealousy",
        "tm:metalsound",
        "tm:irondefense",
        "tm:nightslash",
        "tm:guillotine",
        "tm:stoneedge",
        "tm:ironhead",
        "tm:stealthrock",
        "tm:falseswipe",
        "tm:xscissor",
        "tm:closecombat",
        "tm:terablast",
        "special:hex",
        "special:poltergeist",
        "special:sistertherapy",
        "special:liquidation",
        "special:woodhammer",
        "special:meteormash",
        "special:supercellslam"
    ],
    "features": [],
    "behaviour": {
        "moving": {
            "walk": {
                "walkSpeed": "0.2"
            },
            "fly": {
                "canFly": true,
                "flySpeedHorizontal": "1.0"
            }
        },
        "dampensVibrations": true,
        "combat": {
            "willFlee": false
        },
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.evilplushie.desc"
    ],
    "drops": {
        "amount": "2",
        "entries": [
            {
                "item": "cobblemon:chople_berry",
                "percentage": 30.0
            },
            {
                "item": "neuromon:baleful_harpoon",
                "percentage": 5.0
            }
        ]
    },
    "eggGroups": ["undiscovered"],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 9,
    "weight": 10,
    "forms": [],
    "labels": [
        "custom",
        "neuroverse"
    ],
    "evolutions": [
        {
            "id": "evilplushie_evilneuro_harpoon",
            "variant": "level_up",
            "result": "evilneuro weapon_of_choice=harpoon",
            "consumeHeldItem": false,
            "learnableMoves": [
                "boom"
            ],
            "requirements": [
                {
                    "variant": "defeat_while_hodling",
                    "heldItem": "neuromon:baleful_harpoon",
                    "target": "",
                    "amount": 30
                }
            ]
        },
        {
            "id": "evilplushie_evilneuro_bat",
            "variant": "level_up",
            "result": "evilneuro weapon_of_choice=bat",
            "consumeHeldItem": false,
            "learnableMoves": [
                "boom"
            ],
            "requirements": [
                {
                    "variant": "defeat_while_hodling",
                    "heldItem": "neuromon:ominous_bat",
                    "target": "",
                    "amount": 30
                }
            ]
        },
        {
            "id": "evilplushie_evilneuro_pipe",
            "variant": "level_up",
            "result": "evilneuro weapon_of_choice=pipe",
            "consumeHeldItem": false,
            "learnableMoves": [
                "boom"
            ],
            "requirements": [
                {
                    "variant": "defeat_while_hodling",
                    "heldItem": "neuromon:sinister_pipe",
                    "target": "",
                    "amount": 30
                }
            ]
        },
        {
            "id": "evilplushie_evilneuro_guitar",
            "variant": "level_up",
            "result": "evilneuro weapon_of_choice=guitar",
            "consumeHeldItem": false,
            "learnableMoves": [
                "boom"
            ],
            "requirements": [
                {
                    "variant": "defeat_while_hodling",
                    "heldItem": "neuromon:eerie_guitar",
                    "target": "",
                    "amount": 30
                }
            ]
        }
    ],
    "preEvolution": "studysama"
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/neuroplushie.json
{
    "name": "Neuroplushie",
    "nationalPokedexNumber": 2122,
    "baseStats": {
        "hp": 70,
        "attack": 45,
        "defence": 60,
        "special_attack": 95,
        "special_defence": 75,
        "speed": 95
    },
    "maleRatio": 0.0,
    "catchRate": 3,
    "baseScale": 0.6,
    "baseExperienceYield": 140,
    "baseFriendship": 0,
    "evYield": {
        "special_attack": 2
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 1,
        "height": 1,
        "fixed": false
    },
    "primaryType": "fairy",
    "abilities": [
        "unaware",
        "h:unaware"
    ],
    "shoulderMountable": true,
    "moves": [
        "1:round",
        "1:confusion",
        "1:playnice",
        "1:conversion",
        "5:sing",
        "10:flatter",
        "12:babydolleyes",
        "18:drainingkiss",
        "21:memento",
        "25:playrough",
        "28:conversion2",
        "32:encore",
        "36:roleplay",
        "42:hypervoice",
        "50:nastyplot",
        "56:alluringvoice",
        "60:moonblast",
        "65:healingwish",
        "85:perishsong",
        "tm:pounce",
        "tm:thief",
        "tm:spite",
        "tm:overheat",
        "tm:teleport",
        "tm:confuseray",
        "tm:nightshade",
        "tm:shadowsneak",
        "tm:taunt",
        "tm:alluringvoice",
        "tm:charm",
        "tm:safeguard",
        "tm:protect",
        "tm:scaryface",
        "tm:zenheadbutt",
        "tm:rest",
        "tm:sleeptalk",
        "tm:dazzlinggleam",
        "tm:imprison",
        "tm:psychic",
        "tm:substitute",
        "tm:mistyexplosion",
        "tm:selfdestruct",
        "tm:psychup",
        "tm:mistyterrain",
        "tm:shadowball",
        "tm:lightscreen",
        "tm:reflect",
        "tm:foulplay",
        "tm:psyshock",
        "tm:thunderwave",
        "tm:thunderbolt",
        "tm:trick",
        "tm:terablast",
        "tm:facade",
        "tm:eerieimpulse",
        "tm:helpinghand",
        "tm:wish",
        "tm:trickroom",
        "tm:psychicnoise",
        "tm:darkpulse",
        "tm:metronome",
        "tm:endure",
        "tm:steelbeam",
        "tm:flashcannon",
        "tm:metalsound",
        "tm:raindance",
        "tm:sunnyday",
        "tm:fling",
        "special:hex",
        "special:poltergeist",
        "special:sistertherapy",
        "special:restart"
    ],
    "features": [],
    "behaviour": {
        "resting": {
            "canSleep": true,
            "willSleepOnBed": true,
            "light": "0-4"
        },
        "moving": {
            "walk": {
                "walkSpeed": "0.2"
            },
            "fly": {
                "canFly": true,
                "flySpeedHorizontal": "1.0"
            }
        },
        "dampensVibrations": true,
        "combat": {
            "willFlee": false
        },
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.neuroplushie.desc"
    ],
    "drops": {
        "amount": "2",
        "entries": [
            {
                "item": "cobblemon:babiri_berry",
                "percentage": 30.0
            },
            {
                "item": "neuromon:heart_transmitter",
                "percentage": 5.0
            }
        ]
    },
    "eggGroups": ["undiscovered"],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 9,
    "weight": 10,
    "forms": [],
    "labels": [
        "custom",
        "neuroverse"
    ],
    "evolutions": [
        {
            "id": "neuroplushie_neurosama",
            "variant": "level_up",
            "result": "neurosama",
            "consumeHeldItem": false,
            "learnableMoves": [
                "restart"
            ],
            "requirements": [
                {
                    "variant": "use_move_while_holding",
                    "heldItem": "neuromon:heart_transmitter",
                    "move": "alluringvoice",
                    "amount": 50
                }
            ]
        }
    ],
    "preEvolution": "studysama"
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/neurosama.json
{
    "name": "Neurosama",
    "nationalPokedexNumber": 2124,
    "baseStats": {
        "hp": 85,
        "attack": 60,
        "defence": 65,
        "special_attack": 145,
        "special_defence": 120,
        "speed": 125
    },
    "maleRatio": 0.0,
    "catchRate": 3,
    "baseScale": 0.5,
    "baseExperienceYield": 306,
    "baseFriendship": 0,
    "evYield": {
        "special_attack": 3
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 1,
        "height": 3.2,
        "fixed": false
    },
    "primaryType": "fairy",
    "abilities": [
        "whenyouregone",
        "h:whenyouregone"
    ],
    "moves": [
        "1:round",
        "1:confusion",
        "1:playnice",
        "1:conversion",
        "5:sing",
        "10:flatter",
        "12:babydolleyes",
        "18:drainingkiss",
        "21:memento",
        "25:playrough",
        "28:conversion2",
        "32:encore",
        "36:roleplay",
        "42:hypervoice",
        "50:nastyplot",
        "56:alluringvoice",
        "60:moonblast",
        "65:healingwish",
        "85:perishsong",
        "tm:pounce",
        "tm:thief",
        "tm:spite",
        "tm:overheat",
        "tm:teleport",
        "tm:confuseray",
        "tm:nightshade",
        "tm:shadowsneak",
        "tm:taunt",
        "tm:alluringvoice",
        "tm:charm",
        "tm:safeguard",
        "tm:protect",
        "tm:scaryface",
        "tm:zenheadbutt",
        "tm:rest",
        "tm:sleeptalk",
        "tm:dazzlinggleam",
        "tm:imprison",
        "tm:psychic",
        "tm:substitute",
        "tm:mistyexplosion",
        "tm:selfdestruct",
        "tm:psychup",
        "tm:mistyterrain",
        "tm:shadowball",
        "tm:lightscreen",
        "tm:reflect",
        "tm:foulplay",
        "tm:psyshock",
        "tm:thunderwave",
        "tm:thunderbolt",
        "tm:trick",
        "tm:terablast",
        "tm:facade",
        "tm:eerieimpulse",
        "tm:helpinghand",
        "tm:wish",
        "tm:trickroom",
        "tm:psychicnoise",
        "tm:darkpulse",
        "tm:metronome",
        "tm:endure",
        "tm:steelbeam",
        "tm:flashcannon",
        "tm:metalsound",
        "tm:raindance",
        "tm:sunnyday",
        "tm:fling",
        "special:hex",
        "special:poltergeist",
        "special:sistertherapy",
        "special:restart"
    ],
    "features": [],
    "behaviour": {
        "moving": {
            "walk": {
                "walkSpeed": "0.4"
            }
        },
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.neurosama.desc"
    ],
    "drops": {
        "amount": "1",
        "entries": [
            {
                "item": "cobblemon:babiri_berry",
                "percentage": 50.0
            },
            {
                "item": "neuromon:heart_transmitter",
                "percentage": 25.0
            }
        ]
    },
    "eggGroups": ["undiscovered"],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 14,
    "weight": 300,
    "labels": [
        "custom",
        "neuroverse"
    ],
    "preEvolution": "neuroplushie"
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/evilneuro.json
{
    "name": "Evilneuro",
    "nationalPokedexNumber": 2125,
    "baseStats": {
        "hp": 100,
        "attack": 135,
        "defence": 120,
        "special_attack": 70,
        "special_defence": 100,
        "speed": 75
    },
    "maleRatio": 0.0,
    "catchRate": 3,
    "baseScale": 0.5,
    "baseExperienceYield": 306,
    "baseFriendship": 0,
    "evYield": {
        "attack": 3
    },
    "experienceGroup": "slow",
    "hitbox": {
        "width": 1,
        "height": 3.2,
        "fixed": false
    },
    "primaryType": "dark",
    "abilities": [
        "abberdemon",
        "h:abberdemon"
    ],
    "moves": [
        "1:scratch",
        "1:flatter",
        "1:swagger",
        "1:leer",
        "5:brutalswing",
        "10:knockoff",
        "12:snarl",
        "18:meanlook",
        "21:frustration",
        "25:alluringvoice",
        "28:faketears",
        "32:torment",
        "36:screech",
        "42:beatup",
        "50:stompingtantrum",
        "56:outrage",
        "60:foulplay",
        "65:spiritbreak",
        "85:bulkup",
        "tm:teleport",
        "tm:confuseray",
        "tm:nightshade",
        "tm:shadowsneak",
        "tm:thief",
        "tm:takedown",
        "tm:protect",
        "tm:metronome",
        "tm:rest",
        "tm:sleeptalk",
        "tm:bodyslam",
        "tm:bodypress",
        "tm:taunt",
        "tm:substitute",
        "tm:focusblast",
        "tm:voltswitch",
        "tm:nastyplot",
        "tm:throatchop",
        "tm:playrough",
        "tm:lashout",
        "tm:disarmingvoice",
        "tm:sing",
        "tm:boomburst",
        "tm:psychicnoise",
        "tm:brickbreak",
        "tm:firepunch",
        "tm:thunderpunch",
        "tm:icepunch",
        "tm:fling",
        "tm:trick",
        "tm:imprison",
        "tm:shadowclaw",
        "tm:reflect",
        "tm:lightscreen",
        "tm:trailblaze",
        "tm:willowisp",
        "tm:darkpulse",
        "tm:burningjealousy",
        "tm:metalsound",
        "tm:irondefense",
        "tm:nightslash",
        "tm:guillotine",
        "tm:stoneedge",
        "tm:ironhead",
        "tm:stealthrock",
        "tm:falseswipe",
        "tm:xscissor",
        "tm:closecombat",
        "tm:terablast",
        "special:hex",
        "special:poltergeist",
        "special:sistertherapy",
        "special:liquidation",
        "special:woodhammer",
        "special:meteormash",
        "special:supercellslam"
    ],
    "features": [],
    "behaviour": {
        "moving": {
            "walk": {
                "walkSpeed": "0.4"
            }
        },
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.evilneuro.desc"
    ],
    "drops": {
        "amount": "1",
        "entries": [
            {
                "item": "cobblemon:chople_berry",
                "percentage": 50.0
            },
            {
                "item": "neuromon:baleful_harpoon",
                "percentage": 25.0
            }
        ]
    },
    "eggGroups": ["undiscovered"],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 14,
    "weight": 300,
    "forms": [],
    "labels": [
        "custom",
        "neuroverse"
    ],
    "preEvolution": "evilplushie"
}
