=== gatekeep06/neuromon/common/scemas/species.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/schemas/entity.schema.json",
    "$defs": {
        "stats": {
            "type": "object",
            "properties": {
                "hp": { "type": "integer" },
                "attack": { "type": "integer" },
                "defence": { "type": "integer" },
                "special_attack": { "type": "integer" },
                "special_defence": { "type": "integer" },
                "speed": { "type": "integer" }
            }
        }
    },
    "type": "object",
    "properties": {
        "name": { "type": "string" },
        "nationalPokedexNumber": { "type": "integer" },
        "baseStats": { "$ref": "#/$defs/stats" },
        "maleRatio": { "type": "number", "minimum": -1.0, "maximum": 1.0 },
        "catchRate": { "type": "integer" },
        "baseScale": { "type": "number" },
        "baseExperienceYield": { "type": "integer" },
        "baseFriendship": { "type": "integer" },
        "evYield": { "$ref": "#/$defs/stats" },
        "experienceGroup": {
            "type": "string",
            "enum": ["erratic", "fast", "medium_fast", "medium_slow", "slow", "fluctuating"]
        },
        "hitbox": {
            "type": "object",
            "properties": {
                "width": { "type": "number" },
                "height": { "type": "number" },
                "eyeHeight": { "type": "number" },
                "fixed": { "type": "boolean" }
            }
        },
        "primaryType": { "type": "string" },
        "secondaryType": { "type": "string" },
        "abilities": {
            "type": "array",
            "items": { "type": "string" }
        },
        "shoulderMountable": { "type": "boolean" },
        "shoulderEffects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": { "type": "string", "examples": ["potion_effect"] },
                    "effect": { "type": "string" },
                    "amplifier": { "type": "number" },
                    "ambient": { "type": "boolean" },
                    "showParticles": { "type":  "boolean"},
                    "showIcon": { "type": "boolean" }
                }
            }
        },
        "moves": {
            "type": "array",
            "items": { "type": "string" }
        },
        "features": {
            "type": "array",
            "items": { "type": "string" }
        },
        "standingEyeHeight": { "type": "number" },
        "swimmingEyeHeight": { "type": "number" },
        "flyingEyeHeight": { "type": "number" },
        "behaviour": {
            "type": "object",
            "properties": {
                "resting": {
                    "type": "object",
                    "properties": {
                        "canSleep": { "type": "boolean" },
                        "times": { "type": "string" },
                        "blocks": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "biomes": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "fluids": {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        "light": { "type": "string" },
                        "depth": { "type": "string", "examples": ["comatose", "normal"] },
                        "canSeeSky": { "type": "boolean" },
                        "skyLight": { "type": "string" },
                        "drowsyChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 },
                        "rouseChance": { "type": "number", "minimum": 0.0, "maximum": 1.0 }
                    }
                },
                "moving": {
                    "type": "object",
                    "properties": {
                        "walk": {
                            "type": "object",
                            "properties": {
                                "canWalk": { "type": "boolean" },
                                "avoidsLand": { "type": "boolean" },
                                "walkSpeed": { "type": "string" }
                            }
                        },
                        "swim": {
                            "type": "object",
                            "properties": {
                                "avoidsWater": { "type": "boolean" },
                                "canSwimInWater": { "type": "boolean" },
                                "swimSpeed": { "type": "string" },
                                "canBreatheUnderwater": { "type": "boolean" },
                                "canWalkOnWater": { "type": "boolean" },
                                "canSwimInLava": { "type": "boolean" },
                                "canBreatheUnderlava": { "type": "boolean" },
                                "canWalkOnLava": { "type": "boolean" }
                            }
                        },
                        "fly": {
                            "type": "object",
                            "properties": {
                                "canFly": { "type": "boolean" },
                                "flySpeedHorizontal": { "type": "string" }
                            }
                        },
                        "stepHeight": { "type": "number" },
                        "wanderChance": { "type": "integer" },
                        "wanderSpeed": { "type": "number" },
                        "canLook": { "type": "boolean" }
                    }
                },
                "idle": {
                    "type": "object",
                    "properties": {}
                },
                "fireImmune": { "type": "boolean" },
                "dampensVibrations": { "type": "boolean" },
                "entityInteract": {
                    "type": "object",
                    "properties": {
                        "avoidedByCreeper": { "type": "boolean" },
                        "avoidedByPhantom": { "type": "boolean" },
                        "avoidedByFox": { "type": "boolean" },
                        "avoidedBySkeleton": { "type": "boolean" }
                    }
                },
                "lightningHit": {
                    "type": "object",
                    "properties": {
                        "rotateFeatures": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": { "type": "string" },
                                    "chain": { 
                                        "type": "array",
                                        "items": { "type": "string" }
                                    }
                                }
                            }
                        }
                    }
                },
                "blockInteract": {
                    "type": "object",
                    "properties": {
                        "immuneToSweetBerryBushBlock": { "type": "boolean" },
                        "canStandOnPowderSnow": { "type": "boolean" },
                        "canPathThroughSaccLeaves": { "type": "boolean" }
                    }
                },
                "combat": {
                    "type": "object",
                    "properties": {
                        "willDefendSelf": { "type": "boolean" },
                        "willFlee": { "type": "boolean" },
                        "willDefendOwner": { "type": "boolean" },
                        "fightsMelee": { "type": "boolean" }
                    }
                },
                "herd": {
                    "type": "object",
                    "properties": {
                        "toleratedLeaders": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "pokemon": { "type": "string" },
                                    "tier": { "type": "integer" },
                                    "ignoresLevel": { "type": "boolean" },
                                    "followDistance": { "type": "string" }
                                }
                            }
                        },
                        "maxSize": {"type": "integer" },
                        "followDistance": { "type": "string" }
                    }
                },
                "characteristicRainbow": { "type": "boolean" },
                "itemInteract": {
                    "type": "object",
                    "properties": {
                        "desiredItems": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "item": { "type": "string" },
                                    "pickupPriority": { "type": "integer" },
                                    "fullnessValue": { "type": "integer" },
                                    "returnItem": { "type": "string" },
                                    "onUseEffect": { "type": "string"}
                                }
                            }
                        }
                    }
                }
            }
        },
        "pokedex": {
            "type": "array",
            "items": { "type": "string" }
        },
        "drops": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "amount": { "type": "string" }
            }
        },
        "eggCycles": { "type": "integer" },
        "eggGroups": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["monster", "water_1", "bug", "flying", "field", "fairy", "grass", "human_like", "water_3", "mineral", "amorphous", "water_2", "ditto", "dragon", "undiscovered"]
            }
        },
        "dynamaxBlocked": { "type": "boolean" },
        "implemented": { "type": "boolean" },
        "baseAI": {
            "type": "array",
            "items": { "type": "object" }
        },
        "ai": {
            "type": "array",
            "items": { "type": "object" }
        },
        "height": { "type": "number" },
        "weight": { "type": "number" },
        "forms": {
            "type": "array",
            "items": { "type": "object" }
        },
        "riding": { "type": "object" },
        "labels": {
            "type": "array",
            "items": { "type": "string" }
        },
        "evolutions": {
            "type": "array",
            "items": { "type": "object" }
        },
        "preEvolution": { "type": "string" },
        "battleTheme": { "type": "string" },
        "lightingData": {
            "type": "object",
            "properties": {
                "lightLevel": { "type": "integer" },
                "liquidGlowMode": {
                    "type": "string",
                    "enum": ["LAND", "UNDERWATER", "BOTH"]
                }
            }
        }
    }
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/staz.json
{
    "name": "Staz",
    "nationalPokedexNumber": 2128,
    "baseStats": {
        "hp": 80,
        "attack": 30,
        "defence": 60,
        "special_attack": 30,
        "special_defence": 75,
        "speed": 180
    },
    "maleRatio": 1.0,
    "catchRate": 45,
    "baseScale": 0.8,
    "baseExperienceYield": 100,
    "baseFriendship": 70,
    "evYield": {
        "speed": 2
    },
    "experienceGroup": "medium_slow",
    "hitbox": {
        "width": 1,
        "height": 2,
        "fixed": false
    },
    "primaryType": "psychic",
    "abilities": [
        "trace",
        "keeneye",
        "h:shadowtag"
    ],
    "moves": [
        "1:teleport",
        "1:mirrorcoat",
        "1:counter",
        "1:foresight",
        "5:imprison",
        "7:detect",
        "10:skillswap",
        "12:trick",
        "16:encore",
        "20:confusion",
        "24:safeguard",
        "26:rest",
        "26:sleeptalk",
        "32:amnesia",
        "35:destinybond",
        "40:psychicterrain",
        "50:reflect",
        "50:lightscreen",
        "tm:painsplit",
        "tm:trickroom",
        "tm:rest",
        "tm:sleeptalk",
        "tm:reflect",
        "tm:lightscreen",
        "tm:taunt",
        "tm:metronome",
        "tm:charm",
        "tm:confuseray",
        "tm:disable",
        "tm:embargo",
        "tm:fairylock",
        "tm:flatter",
        "tm:swagger",
        "tm:followme",
        "tm:gravity",
        "tm:hypnosis",
        "tm:mistyterrain",
        "tm:psychup",
        "tm:recycle",
        "tm:raindance",
        "tm:sunnyday",
        "tm:spotlight"
    ],
    "features": [],
    "behaviour": {
        "herd": {
            "maxSize": 10,
            "toleratedLeaders": [
                {
                    "pokemon": "vedal",
                    "tier": 1,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.staz.desc"
    ],
    "drops": {
        "amount": "1",
        "entries": [
            {
                "item": "cobblemon:black_glasses",
                "percentage": 10.0
            }
        ]
    },
    "eggCycles": 20,
    "eggGroups": [
        "field",
        "human_like"
    ],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 15,
    "weight": 400,
    "labels": [
        "custom",
        "neuroverse"
    ]
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/gymbag.json
{
    "name": "Gymbag",
    "nationalPokedexNumber": 2127,
    "baseStats": {
        "hp": 60,
        "attack": 95,
        "defence": 75,
        "special_attack": 50,
        "special_defence": 65,
        "speed": 85
    },
    "maleRatio": 0.5,
    "catchRate": 75,
    "baseScale": 0.75,
    "baseExperienceYield": 150,
    "baseFriendship": 50,
    "evYield": {
        "attack": 1
    },
    "experienceGroup": "medium_fast",
    "hitbox": {
        "width": 0.9,
        "height": 1.9,
        "fixed": false
    },
    "primaryType": "steel",
    "secondaryType": "flying",
    "abilities": [
        "tintedlens",
        "klutz",
        "h:infiltrator"
    ],
    "moves": [
        "1:odorsleuth",
        "1:tackle",
        "4:swagger",
        "5:headbutt",
        "6:gust",
        "10:doublehit",
        "12:recycle",
        "16:encore",
        "20:metalsound",
        "24:knockoff",
        "26:ironhead",
        "32:batonpass",
        "34:lockon",
        "35:reflect",
        "36:thunderwave",
        "40:selfdestruct",
        "44:whirlwind",
        "50:gunkshot",
        "55:shiftgear",
        "egg:switcheroo",
        "egg:autotomize",
        "egg:refresh",
        "egg:tickle",
        "egg:copycat",
        "tm:lightscreen",
        "tm:protect",
        "tm:rest",
        "tm:sleeptalk",
        "tm:thunder",
        "tm:thunderbolt",
        "tm:trickroom",
        "tm:substitute",
        "tm:irondefense",
        "tm:lastresort",
        "tm:endure",
        "tm:facade",
        "tm:signalbeam",
        "tm:defog",
        "tm:voltswitch",
        "tm:magnetbomb",
        "tm:rapidspin",
        "tm:uproar",
        "tm:fly",
        "tm:aerialace",
        "tm:playrough",
        "tm:detect",
        "tm:willowisp",
        "tm:confuseray",
        "tm:metronome",
        "tm:flash",
        "tm:spikes",
        "tm:poisonjab",
        "tutor:toxic",
        "tutor:mistyexplosion",
        "tutor:playrough",
        "tutor:toxicspikes",
        "tutor:gravity"
    ],
    "features": [],
    "behaviour": {
        "resting": {
            "canSleep": true,
            "willSleepOnBed": true,
            "depth": "normal",
            "light": "0-4"
        },
        "moving": {
            "fly": {
                "canFly": true
            },
            "walk": {
                "canWalk": false
            },
            "wanderChance": 60
        },
        "herd": {
            "maxSize": 10,
            "followDistance": "2-4",
            "toleratedLeaders": [
                {
                    "pokemon": "gymbag shiny=false",
                    "tier": 1
                },
                {
                    "pokemon": "gymbag shiny",
                    "tier": 2
                },
                {
                    "pokemon": "vedal",
                    "tier": 3,
                    "ignoresLevel": true
                },
                {
                    "pokemon": "studysama",
                    "tier": 4,
                    "ignoresLevel": true
                },
                {
                    "pokemon": "neuroplushie",
                    "tier": 5,
                    "ignoresLevel": true
                },
                {
                    "pokemon": "evilplushie",
                    "tier": 5,
                    "ignoresLevel": true
                },
                {
                    "pokemon": "neurosama",
                    "tier": 6,
                    "ignoresLevel": true
                },
                {
                    "pokemon": "evilneuro",
                    "tier": 6,
                    "ignoresLevel": true
                }
            ]
        }
    },
    "pokedex": [
        "cobblemon.species.gymbag.desc"
    ],
    "drops": {
        "amount": "1",
        "entries": [
            {
                "item": "minecraft:raw_iron",
                "quantityRange": "0-3"
            }
        ]
    },
    "eggCycles": 15,
    "eggGroups": [
        "bug"
    ],
    "dynamaxBlocked": false,
    "implemented": true,
    "height": 4,
    "weight": 12,
    "labels": [
        "custom",
        "neuroverse"
    ]
}

=== gatekeep06/neuromon/common/src/main/resources/data/cobblemon/species/custom/cerby.json
{
    "name": "Cerby",
    "nationalPokedexNumber": 2131,
    "baseStats": {
        "hp": 80,
        "attack": 95,
        "defence": 70,
        "special_attack": 40,
        "special_defence": 70,
        "speed": 85
    },
    "maleRatio": 0.5,
    "catchRate": 90,
    "baseScale": 0.75,
    "baseExperienceYield": 40,
    "baseFriendship": 50,
    "evYield": {
        "hp": 1
    },
    "experienceGroup": "medium_fast",
    "hitbox": {
        "width": 1,
        "height": 1,
        "fixed": false
    },
    "primaryType": "normal",
    "abilities": [
        "guarddog",
        "h:guarddog"
    ],
    "moves": [

    ],
    "features": [],
    "behaviour": {

    },
    "pokedex": [

    ],
    "drops": {

    },
    "eggCycles": 120,
    "eggGroups": ["field", "fairy"],
    "dynamaxBlocked": false,
    "implemented": false,
    "height": 1,
    "weight": 1,
    "labels": [
        "custom",
        "neuroverse"
    ]
}
